const LOCALITIES = [
  "Adarsh Nagar",
  "Aishbagh",
  "Aishbagh Stadium",
  "Akbari Gate",
  "Alambagh",
  "Alambagh Bus Stand",
  "Alamnagar",
  "Aliganj",
  "Aliganj Sector H",
  "Aliganj Sector K",
  "Aliganj Sector O",
  "Amausi",
  "Amausi Airport",
  "Amar Shaheed Path",
  "Aminabad",
  "Aminabad West",
  "Ansal API",
  "Ansal Golf Link",
  "Asharfabad",
  "Ashiana",
  "Ashiana Colony",
  "Ashok Marg",
  "Aurangabad Khalsa",
  "Awadh Vihar Yojna",
  "Azad Nagar",
  "Bakshi Ka Talab",
  "Balaganj",
  "Bangla Bazaar",
  "Banthra",
  "Barabanki Road",
  "BBD City",
  "BBD University",
  "Begum Hazrat Mahal Park",
  "Bijnor",
  "Bijnor Road",
  "Brahmapuri Colony",
  "Butler Colony",
  "Cantonment",
  "Chandralok",
  "Charbagh",
  "Charbagh Station",
  "Chaupatiyan",
  "Chikmandi",
  "Chinhat",
  "Chinhat Crossing",
  "Chowk",
  "Civil Lines",
  "Dalibagh",
  "Daliganj",
  "Deva Road",
  "Dilkusha",
  "Dubagga",
  "Eldeco Shaheed Path",
  "Eldeco Udyan",
  "Eldeco Udyan 2",
  "Engineering College",
  "Engineering College Chauraha",
  "Faizabad Road",
  "Faridi Nagar",
  "Fatehganj",
  "Fatehpur",
  "Ganeshganj",
  "Gayatri Vihar",
  "Golaganj",
  "Gomti Nagar",
  "Gomti Nagar Extension",
  "Gomti Nagar Extension Sector 1",
  "Gomti Nagar Extension Sector 2",
  "Gomti Nagar Extension Sector 3",
  "Gomti Nagar Extension Sector 4",
  "Gomti Nagar Extension Sector 5",
  "Gomti Nagar Extension Sector 6",
  "Gomti Nagar Extension Sector 7",
  "Gosainganj",
  "Gwynne Road",
  "HAL Colony",
  "Halwasiya Market",
  "Hardoi Road",
  "Hazratganj",
  "Hewett Road",
  "High Court Colony",
  "Husainganj",
  "Hussainabad",
  "IIM Lucknow",
  "IIM Road",
  "Indira Nagar",
  "Indira Nagar Sector 1",
  "Indira Nagar Sector 2",
  "Indira Nagar Sector 3",
  "Indira Nagar Sector 4",
  "Indira Nagar Sector 5",
  "Indira Nagar Sector 6",
  "Indira Nagar Sector 7",
  "Indira Nagar Sector 8",
  "Indira Nagar Sector 9",
  "Indira Nagar Sector 10",
  "Indira Nagar Sector 11",
  "Indira Nagar Sector 12",
  "Indira Nagar Sector 14",
  "Indira Nagar Sector 15",
  "Indira Nagar Sector 16",
  "Indira Nagar Sector 17",
  "Indira Nagar Sector 18",
  "Indira Nagar Sector 19",
  "Indira Nagar Sector 20",
  "Indira Nagar Sector 21",
  "Indira Nagar Sector 22",
  "Indira Nagar Sector 23",
  "Indira Nagar Sector 24",
  "Indira Nagar Sector 25",
  "Ismailganj",
  "IT College",
  "Itaunja",
  "Jahangirabad",
  "Jankipuram",
  "Jankipuram Extension",
  "Jankipuram Sector F",
  "Jankipuram Yojna",
  "Jopling Road",
  "Judges Colony",
  "Juggaur",
  "Kaiserbagh",
  "Kakori",
  "Kalyanpur",
  "Kamta",
  "Kanpur Road",
  "Kapoorthala",
  "Kashmiri Mohalla",
  "Khurram Nagar",
  "Krishna Nagar",
  "Kursi Road",
  "La Martiniere",
  "Lalbagh",
  "Lalkuan",
  "LDA Colony",
  "LDA Colony Sector A",
  "LDA Colony Sector B",
  "LDA Colony Sector C",
  "LDA Colony Sector D",
  "LDA Colony Sector E",
  "LDA Colony Sector F",
  "LDA Colony Sector G",
  "LDA Colony Sector H",
  "LDA Colony Sector I",
  "LDA Colony Sector J",
  "LDA Colony Sector K",
  "LDA Colony Sector L",
  "LDA Colony Sector M",
  "LDA Colony Sector N",
  "LDA Picnic Spot",
  "Lekhraj Market",
  "Madiyaon",
  "Mahanagar",
  "Mahanagar Extension",
  "Mahatma Gandhi Marg",
  "Mahona",
  "Malihabad",
  "Malhaur",
  "Maulviganj",
  "Model House",
  "Mohanlalganj",
  "Mohibullapur",
  "Munshi Pulia",
  "Nadan Mahal",
  "Nadarganj",
  "Naka Hindola",
  "Nakhas",
  "Narhi",
  "Nazirabad",
  "New Hyderabad",
  "New Nirala Nagar",
  "Nirala Nagar",
  "Nishatganj",
  "Nishatganj Pulia",
  "Omaxe City",
  "Omaxe Residency",
  "Paper Mill Colony",
  "Para",
  "Park Road",
  "Picnic Spot Road",
  "Polytechnic",
  "Polytechnic Chauraha",
  "Prabandh Nagar",
  "Purania",
  "Qaisarbagh",
  "Rae Bareli Road",
  "Rahimabad",
  "Railway Colony",
  "Raja Bazaar",
  "Rajajipuram",
  "Rajajipuram Sector 1",
  "Rajajipuram Sector 2",
  "Rajajipuram Sector 3",
  "Rajajipuram Sector 4",
  "Rajajipuram Sector 5",
  "Rajajipuram Sector 6",
  "Rajajipuram Sector 7",
  "Rajajipuram Sector 8",
  "Rajajipuram Sector 9",
  "Rajajipuram Sector 10",
  "Rajajipuram Sector 11",
  "Rajajipuram Sector 12",
  "Rajajipuram Sector 13",
  "Rajendra Nagar",
  "Rakabganj",
  "Residency",
  "River Bank Colony",
  "Saadatganj",
  "Sadar Bazaar",
  "Sahara City Homes",
  "Sahara States",
  "Sapru Marg",
  "Sarojini Nagar",
  "Sector 6 Vrindavan Yojna",
  "SGPGIMS",
  "Shaheed Path",
  "Shalimar One World",
  "Sitapur Road",
  "Sitapur Yojna",
  "South City",
  "Sultanpur Road",
  "Surajkund",
  "Sushant Golf City",
  "Talkatora",
  "Tedhi Pulia",
  "Telibagh",
  "Thakurganj",
  "Tikait Rai Talab",
  "Transport Nagar",
  "Triveni Nagar",
  "Triveni Nagar 2",
  "Triveni Nagar 3",
  "Utrathia",
  "Vastu Khand",
  "Vibhav Khand",
  "Vibhuti Khand",
  "Victoria Street",
  "Vidhan Sabha Marg",
  "Vijay Khand",
  "Vijayant Khand",
  "Vikalp Khand",
  "Vikas Khand",
  "Vikas Nagar",
  "Vikrant Khand",
  "Vinamra Khand",
  "Vinay Khand",
  "Vineet Khand",
  "Vipin Khand",
  "Vipul Khand",
  "Viraj Khand",
  "Viram Khand",
  "Virat Khand",
  "Vrindavan Yojna",
  "Vishesh Khand",
  "Vishal Khand",
  "Vishwas Khand",
  "Vivek Khand",
  "Wazirganj",
  "Yahiyaganj",
];
